semantic-release/github

lib/publish.js
test/integration.test.js
test/publish.test.js

Do not create the tag if it has already been created by another plugin like `apm` or `git`.

Skip tag creation if it already exists

---

package.json
test/integration.test.js
test/publish.test.js
test/verify.test.js

Store only objects set in `beforeEach` used in `test`.
Avoid logging useless info on test failure.

Refactor test context

---

README.md
lib/resolve-config.js
test/helpers/mock-github.js
test/integration.test.js
test/publish.test.js
test/verify.test.js

Allowing to set the `githubToken` in the configuration is not particularly useful and create a security risk. If users sets it in their config locally and commit the change by mistake their token would be exposed.
To be safer, it's probably better to allow to configure the Github token only via environment variable.

Remove `githubToken` from options

---

lib/get-client.js
package.json

See https://github.com/octokit/rest.js/releases/tag/v14.0.0
This will avoid getting warnings when installing semantic-release.

Migrate to the new name of the github api client

---

README.md
index.js
lib/definitions/errors.js
lib/definitions/sr-issue-id.js
lib/fail.js
lib/find-sr-issues.js
lib/get-error.js
lib/get-fail-comment.js
lib/get-success-comment.js
lib/publish.js
lib/resolve-config.js
lib/success.js
lib/verify.js
package.json
test/fail.test.js
test/find-sr-issue.test.js
test/get-fail-comment.test.js
test/get-success-comment.test.js
test/integration.test.js
test/publish.test.js
test/success.test.js
test/verify.test.js

Add success and fail plugin hooks

---

lib/get-search-queries.js
lib/success.js
test/get-search-queries.test.js
test/integration.test.js
test/success.test.js

Fix #34
It turns out the GitHub API access a query string of maximum 256 characters for the [search issue](https://developer.github.com/v3/search/#search-issues) endpoint.
This PR craft queries to fit that limit. The minimum number of queries possible will be executed.

fix: make search queries of 256 characters maximum

---

lib/fail.js
lib/get-client.js
lib/glob-assets.js
lib/publish.js
lib/success.js
lib/verify.js
package.json
test/fail.test.js
test/find-sr-issue.test.js
test/get-client.test.js
test/glob-assets.test.js
test/integration.test.js
test/publish.test.js
test/success.test.js
test/verify.test.js

Fix #37, Fix semantic-release/semantic-release#607, Fix semantic-release/semantic-release#658.
[Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) based implementation to retry and throttle the GitHub client API calls.
The implementation:
- Throttle the calls per limit rate group (The GitHub API has different limit rate for the `search` endpoints and core endpoints) => All calls to core endpoints share the same rate limit.
- Memoize the throttler function to instantiated at most one throttler per limit rate group
- Retry the calls and throttle each retries based on the rate limit group
- Do not modify the Octokit instance
- So not preemptively wrap the Octokit instance functions => Only the called function are intercepted and throttled/retried …

feat: throttle and retry GitHub API calls.

---

lib/get-client.js
package.json
test/fail.test.js
test/find-sr-issue.test.js
test/get-client.test.js
test/publish.test.js
test/success.test.js
test/verify.test.js

Due to sindresorhus/p-throttle#6 a timeout would stay active until and prevent Node to exit properly.
This PR replace `p-throttle` with [bottleneck](https://github.com/SGrondin/bottleneck).
The core request are limited at one per 720ms instead of 5000 per hours and search ones at one per 2s instead of 30 per minutes. This is because `bottleneck` only supports limiting at a frequency of 1 per XX with the `minTime` options.
The `reservoir` option could be used but there is now way as of now to handle the situation where the reservoir get exhausted (Bottleneck just returns without errors and dropping the jobs not executed yet).
That result in a slightly less optimized processing of request. In the case of `search` request:
- Before they would be throttled at 1 per second, then after 30 …

fix: replace `p-throttle` with `bottleneck`

---

lib/get-client.js

`null` does not get overwritten by _.defaults which `@octokit/rest` v15+ is using

Default octokit protocol option to undefined

---

lib/success.js
package.json
test/integration.test.js
test/success.test.js

Fix semantic-release/semantic-release#726
- add comment only to merged PRs
- add comment only to closed issues/PRs
- do not add comment for unrelated PR returned by search

Filter out issues/PRs in which to comment on success

---

lib/success.js
test/integration.test.js
test/success.test.js

On GitHub, when PRs are merged via "Rebase and merged" the commit sha change, therefore comparing the shas of the release commits with the shas of the PRs found fails.
This PR use the tree sha, which stays unchanged on "Rebase and merge", as a backup to verify the PRs found contains on of the release commit.

fix: compare release and PR commits with tree sha

---

lib/get-fail-comment.js

Just got a comment at https://github.com/electron/i18n/issues/321 which is awesome! So helpful.
Noticed a typo though. This PR should fix it.
cc @pvdlg

fix typo in failure comment

---

lib/success.js
package.json
test/success.test.js

Allow to parse issue referenced with both `Fix #1` and `Fix https://github.com/owner/repo/issues/1`.
Works also for PRs (`Fix https://github.com/owner/repo/pull/1`) and with custom GitHub URL (`Fix https://my-ghe.com/owner/repo/issues/1`).

feat: parse issue referenced with full URL

---

lib/definitions/rate-limit.js
lib/get-client.js
test/fail.test.js
test/find-sr-issue.test.js
test/get-client.test.js
test/helpers/rate-limit.js
test/integration.test.js
test/publish.test.js
test/success.test.js
test/verify.test.js

Fix semantic-release/semantic-release#843
This PR fix 2 problems related to rate limiting:
- Add 10% of "safety margin" on top of the GitHub recommended rate (i.e the `search` endpoint has a rate of 1 call every 2 seconds, however the [`rate limit exceeded` is still triggered](https://github.com/semantic-release/semantic-release/issues/843#issue-337790316))
- Limit calls modify data and generate notification to 1 every 3 seconds (value obtained with empirical tests on the public API) to solve https://github.com/semantic-release/semantic-release/issues/843#issuecomment-404999136
This PR do not handle the `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. This will be implemented in the GitHub API client.

fix: rate limit write function further

---

lib/success.js
test/integration.test.js
test/success.test.js

Contrary to the assumption made in #60 there is certain cases where "Rebase and merged" creates commits with a different tree sha.
That happens when the feature branch is behind the base branch, but if there is no conflicts, GitHub allows to merge with "Rebase and Merge".
In the case of "Squash and Merge" the squashed commit also has a different tree sha than the commits on the feature branch.
The algorithm now works as follow:
- semantic-release knows only about the commits on `master` included in the release. Those commits are the result of "Create a Merge commit", "Squash and Merge" or "Rebase and Merge"
- the plugin do a GitHub search issue to find the PRs associated with the commits part of the release
- GitHub returns the associated PR, but also sometimes some unrelated ones (see …

fix: compare release and PR commits with merge_commit_sha

---

lib/get-client.js
test/get-client.test.js

/cc @gr2m 
So I'm not super satisfied with the mocking strategy that relies on on `nock`.
The problem is that we add the processing time on `nock` which affect the time measured between 2 calls. So that could make the test less reliable on a very slow machine (the measurement buffer is 50 ms though).
@gr2m do you know if there is a way to stub the `request` function passed to the callback of `github.hook.wrap`? That would allow to completely bypass the http requests in the `get-client` tests so we wouldn't need `nock` in there.

fix: use `octokit.hook.wrap` rather than Proxies

---

README.md
lib/fail.js
lib/get-fail-comment.js
test/fail.test.js
test/get-fail-comment.test.js
test/integration.test.js

fix: retrieve the branch name from `context.branch`

---

lib/success.js
test/success.test.js

It turns out [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/) in PRs closes issues only when the PR get merged to the default branch.
So when merging a PR to `next` or `beta` the fixed issue is not closed so `@semantic-release/github` doesn't comment it.
This PR removes this check and we now comment on each issue fixed by a commit or its associated PR, even if GitHub didn't close the resolved issue.

fix: also add comment/label to open issues

---

lib/fail.js
lib/success.js

- The goal of this PR to correct the deprecated param from octokit/rest.
- Calling with deprecated param will get this warning
```
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for ".pullRequests.listCommits()". Use "pull_number" instead
at Object.keys.forEach.key (/Users/sbtrung/.nvm/versions/node/v10.12.0/lib/node_modules/semantic-release/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:73:26)
at Array.forEach (<anonymous>)
at Object.patchedMethod [as listCommits] (/Users/sbtrung/.nvm/versions/node/v10.12.0/lib/node_modules/semantic-release/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:69:26)
at pFilter (/Users/sbtrung/.nvm/versions/node/v10.12.0/lib/node_modules/semantic-release/node_modules/@semantic-release/git …
```

fix: adapt for latest @octokit/rest to remove deprecation warnings

---

lib/add-channel.js
lib/is-prerelease.js
test/add-channel.test.js
test/integration.test.js
test/publish.test.js

That will avoid wrongly setting `prereleasae` to `true` in case of the main branch defining a custom `channel`.

fix: use the `branch.main` flag to determine is the release need the `prerelease` flag

---

README.md
lib/resolve-config.js
test/helpers/mock-github.js
test/publish.test.js

fix: publish a release when env.GITHUB_URL is set to https://github.com

---

lib/verify.js
test/verify.test.js

Similar to Github Actions, when using installation tokens from Github Apps the verification should be skipped.
Should we use a more generic flag for skipping the permission validation? e.g. `SKIP_PERMISSIONS`?
I will add the relevant docs to the Readme once I get the ok.

fix: skip permission verification exception when Github Apps

---

README.md
lib/definitions/errors.js
lib/get-release-links.js
lib/publish.js
lib/resolve-config.js
lib/success.js
lib/verify.js
test/get-release-links.test.js
test/success.test.js
test/verify.test.js

A new option `addReleases` has been added.
Setting this option will instruct the plugin to append all
additional releases to the Github release on the top.
Closes #281

feat: add additional release links to the release

---

.github/workflows/test.yml

I was discussing with @travi to use this change as a starting point to adapt https://adr.github.io/ as we are both interested in ADR

ci: remove double builds for renovate

---

README.md

Document the minimum required permissions of the default GitHub Actions `GITHUB_TOKEN` token needed to use this plugin.
Closes #456

docs: add GitHub Actions default token permission requirements

---

README.md

Update the documentation of the minimum required permissions of the default GitHub Actions `GITHUB_TOKEN` token needed to use this plugin. In my previous pull request I used the wrong key for the `contents` and `pull-requests` permission (apologies for that, found out about it only after trying to create a release with an invalid workflow :sweat_smile:).
You can view [the permissions documentation](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) to verify this change. Also, [this CI run](https://github.com/birjolaxew/svglint/runs/4725048163) that's based on [this workflow file](https://github.com/birjolaxew/svglint/blob/3ab00548d0df619a9a1f751ff303065035b5dbf7/.github/workflows/release.yml) shows the documentation is now correct. …

docs: fix name of GitHub Actions permissions

---

lib/definitions/retry.js

Potential fix to #644 
The current retry logic attempts to see if the retry limit has been hit but it does this by checking against an undefined value.
This may have been an oversight from #487 as `RETRY_CONFIG` did have a `retries` property, but it was removed.

fix: define retry limit in retry config

---

lib/publish.js
test/publish.test.js

Hello,
I’ve just realized that if a user publish release with asset(s) , the discussion will not be created with the previous setting. I’m really sorry for that. 🤦‍♂️But hopefully, I’ve fixed it with this PR.
Thanks for reviewing it again!

fix: discussion not created if publishing release with assets

---

.github/workflows/test.yml
package-lock.json
package.json

BREAKING CHANGE: node v18 and v19 are no longer supported

feat(node-versions): dropped support for node v18 and v19

---

README.md
lib/add-channel.js
lib/fail.js
lib/octokit.js
lib/publish.js
lib/resolve-config.js
lib/success.js
lib/verify.js
test/verify.test.js

Server and API endpoints can be different. Some code parts, e.g. issue parsing, need the server endpoint and we should make this explicit. The existing `githubApiPathPrefix` option is not sufficient when the API is served from a different host (like `api.github.com`).
Fixes #827
:hammer_and_pick: with :heart: by [Siemens](https://opensource.siemens.com/)

fix: introduce dedicated option for GitHub API endpoint

---

package.json

Eg: _A GitHub personal token (https://github.com/semantic-release/github#readme/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment._ is the currently generated error message. 
This PR will fix the link in the error being invalid.

Fixed homepage link in package.json so the generated links in the errors are valid

---

lib/definitions/errors.js
lib/verify.js
test/integration.test.js
test/verify.test.js

This Pull request introduces an extra step in the plugin `verify` lifecycle which verifies that the `repositoryUrl` and/or project package.json's `repository` field matches the project's current GitHub URL. This throws an error `EMISMATCHGITHUBURL` which confirms mismatch and suggests a fix.
**Changes Made**
- Added a logic that requests the repo details leveraging the github get-a-repository endpoint, and checks for a `status` of `200` and a match between the response data's `clone_url` value and the `context.options.repositoryUrl`. And it should only run this when we a `githubToken` is authenticated and we do not have the `EINVALIDPROXY` and `EMISSINGREPO` error.
```js
if (
owner &&
repo &&
githubToken &&
!errors.find(({ code }) => code === "EINVALIDPROXY") &&
!errors.find(({ code }) => …
```

fix: failing release due to renamed repository

---

lib/success.js
test/integration.test.js
test/success.test.js

This Pull Request addresses the following edge cases in our consumption of GraphQL at fetching `associatedPRs` for `context.commits` list in the `success` lifecycle of the plugin.
We currently use GraphQL Fragments to query `associatedPRs` for each commit in the `context.commits` array, this grants us the ability to get `associatedPRs` for alot of commits by making just one request. BUT, we are limited to a fragment of only 100 items which means that we can only query `associatedPRs` for 100 commits in one request, and needing to make another request for the next set of 100 incases where there's more than 100.
**THE FIX**: Implemented logic to split the `context.commits` array into chunks of 100 items, which is then consumed by the `buildAssociatedPRsQuery` utils that builds the GraphQL …

fix(edge-case): fetching `associatedPRs` on 100+ `context.commits` in `success` lifecycle

---

lib/verify.js
test/verify.test.js

fix: ignore case when checking for repo rename

---

lib/definitions/errors.js
lib/verify.js
test/integration.test.js
test/verify.test.js

Solves #895 for classic PATs only

feat: verify OAuth scopes of classic GitHub PATs

---

lib/success.js

The PR addressed the issue where we our graphql query that fetches associatedPRs hits a case where it requests for 1million plus nodes exceeding the GitHub Node Limits size. It does this by simply reducing the number of `labels` requested per associatedPRs reducing the maximum possible requests to `410,000` just right below `500,000` which is GitHub's maximum Node Limit size.
**Changes Made:**
- Updated the `first` value in the `baseField` constant from `100` to `40` for all graphql request that consumes it 😁 
Fixes #911

fix: `max_node_limit_exceeded` error when fetching associatedPRs

---

lib/definitions/errors.js
lib/verify.js
test/integration.test.js
test/verify.test.js

This PR Reverts the changes introduced in semantic-release/github#897
Resolves #914

fix: Revert: feat: verify OAuth scopes of classic GitHub PATs

---

lib/glob-assets.js

remove unnecessary option when invoking `globby()`: `gitignore: false`
The default behaviour of `gitignore` option is `false`[^1]
[^1]: https://github.com/sindresorhus/globby?tab=readme-ov-file#gitignore

fix(glob-assets): remove unnecessary option when invoking `globby()`

---

README.md

<a href='https://hearts.dev/projects/3/users/jedwards1211'><img width='50' alt='' align='right' src='https://hearts.dev/projects/3/users/jedwards1211/tally.svg'></a>

docs(README.md): fix descriptions of condition options

---

lib/find-sr-issues.js
lib/success.js
test/fail.test.js
test/find-sr-issue.test.js
test/integration.test.js
test/success.test.js

<a href='https://hearts.dev/projects/3/users/babblebey'><img width='50' alt='' align='right' src='https://hearts.dev/projects/3/users/babblebey/tally.svg'></a>
This PR completely removes the consumption of the github search API from the plugin; following its relegation in https://github.com/semantic-release/github/pull/907 and the deprecation notice of the endpoint itself from github.
BREAKING CHANGE
`@semantic-release/github` no longer consumes the GitHub Search API in the plugin
Fixes #1022

feat: deprecate github search api consumption
