package.json
test/integration.test.js
test/publish.test.js

Update github to the latest version 🚀

---

index.js
lib/publish.js
lib/verify.js
package.json
test/integration.test.js
test/publish.test.js
test/verify.test.js

See semantic-release/semantic-release#524

Make semantic-release language agnostic

---

README.md
lib/glob-assets.js
lib/publish.js
lib/resolve-config.js
lib/verify.js
package.json
test/fixtures/.dotfile
test/glob-assets.test.js
test/helpers/mock-github.js
test/integration.test.js
test/publish.test.js
test/verify.test.js

Fix #4
Also support `github@13.0.0`.

Support globs for the `assets` option

---

package.json
test/helpers/mock-github.js

Update prettier to the latest version 🚀 

---

index.js
lib/get-client.js
lib/publish.js
lib/verify.js
test/integration.test.js
test/verify.test.js

Log the Github url in the `verifyConditions` plugin

---

lib/verify.js
package.json
test/verify.test.js

Fix regression introduced in #15

Handle custom url without prefix

---

README.md
lib/publish.js
lib/verify.js
test/integration.test.js
test/publish.test.js

To be merged before semantic-release/semantic-release#613

feat: do not create Git tag anymore

---

lib/resolve-config.js
test/verify.test.js

fix: handle undefined GitHub prefix

---

lib/success.js
test/success.test.js

Fix semantic-release/semantic-release#682

fix: prevent duplicate comments on PRs

---

lib/success.js
test/success.test.js

Comment only issues/PR on the repository on which the release happens.
Fix #45

fix: do not comment on other repositories

---

lib/get-client.js
package.json
test/verify.test.js

adapt for @octokit/rest@15.2.0

---

lib/verify.js

fix(verify): call GitHub API only if url is valid

---

lib/glob-assets.js
package.json
test/glob-assets.test.js

Add temporary workaround for https://github.com/kevva/dir-glob/issues/7 and https://github.com/mrmlnc/fast-glob/issues/47

fix: add workaround to expand directory when globbing

---

lib/glob-assets.js
test/glob-assets.test.js

fix: deduplicate glob results by resolved path

---

package.json
test/get-client.test.js

chore(package): update @octokit/rest to version 15.13.1

---

lib/fail.js
lib/glob-assets.js
lib/success.js
test/fail.test.js
test/integration.test.js
test/success.test.js

Fix semantic-release/semantic-release#962

Fix assets deduping and handle renamed repos

---

README.md

Add scopes for personal access token

---

.travis.yml
README.md
package.json

Version `16.0.0-beta` has been released for 2 weeks, time to use it ourselves!

chore(package): update semantic-release to version 16.0.0-beta

---

lib/publish.js
test/integration.test.js
test/publish.test.js

Here's a PR as discussed in #163.
Closes #163

Create a draft release when there are assets in the release

---

lib/fail.js
lib/success.js
package.json

It makes the code a bit more readable I think. I don’t mind either way @pvdlg

excempt "issue_number" and "pull_number" from camelcase rule

---

lib/verify.js
test/verify.test.js

Fixes https://github.com/semantic-release/github/issues/182. For the time being, you can install my fork
```
npm install -D @gr2m/semantic-release-github
```

feat: GitHub Actions support

---

.travis.yml

ci(node): set node 8 to 8.3 and add node 12

---

README.md

This reverts commit f862364e6845f9e8b39f0966330a530cf2812561.

revert: doc: fix a dead link in readme(#209)

---

README.md
lib/publish.js
test/integration.test.js

feat: allow to use context variables to generate assets label and name

---

lib/success.js
test/success.test.js

fix: do not fail if forbidden to aadd a comment to an issue

---

lib/fail.js
lib/parse-github-url.js
lib/publish.js
lib/success.js
lib/verify.js
package.json
test/verify.test.js

fix: fix parsing or GitHub URL with special character prefix

---

lib/success.js
package.json
test/find-sr-issue.test.js
test/glob-assets.test.js
test/success.test.js

fix: use correct peerDependencies for semantic-release

---

lib/get-client.js
lib/publish.js
lib/success.js
package.json
test/get-client.test.js

fix: address `@octokit/rest` deprecations

---

README.md

docs: add note on GitHub Actions release events

---

lib/publish.js
test/publish.test.js

feat: set target_commitish when creating a GitHub release 

---

lib/get-fail-comment.js

- Improve user facing text in `lib/get-fail-comment.js`
I found some other small stuff as well, so I'm fixing that in one go. 😄 
Closes #366.

fix: improve text

---

.github/workflows/test.yml
package-lock.json
package.json

closes https://github.com/semantic-release/github/issues/394
BREAKING CHANGE: the minimum required version of node is now v14.17

feat(node-version): raised the minimum required version to v14.17 (#397)

---

package-lock.json
package.json

Reverts semantic-release/github#475

build: revert "chore(deps): update dependency glob-parent to 5.1.2 [security]"

---

test/add-channel.test.js
test/find-sr-issue.test.js
test/success.test.js
test/to-octokit-options.test.js

test: no more need for `test.serial`

---

lib/definitions/errors.js
lib/verify.js
test/integration.test.js
test/verify.test.js

This reverts commit 76fdaa31cd623a3df1c4e51ae1ed4434a24a2c3e.
closes #885. Follow up to #878.
Once we reverted, we can try again, and try to incorporate the fix from #886 - but it should be covered by tests

fix: Revert "fix: failing release due to renamed repository (#878)"

---

lib/find-sr-issues.js
lib/success.js
test/fail.test.js
test/find-sr-issue.test.js
test/integration.test.js
test/success.test.js

<a href='https://hearts.dev/projects/3/users/travi'><img width='50' alt='' align='right' src='https://hearts.dev/projects/3/users/travi/tally.svg'></a>
duplicate of https://github.com/semantic-release/github/pull/1037 originally created by @babblebey in order to bring this change into the stable release channel ahead of other changes from the beta release line.
Fixes https://github.com/semantic-release/github/issues/1022

feat: remove github search api consumption
